#  Welcome to Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

# Array Creation : Conversion from other Python Structures

In [8]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,4)

In [21]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 1.89146896e-307, 1.37961302e-306,
        6.23053614e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 8.90104239e-307, 6.89804132e-307],
       [1.33512376e-306, 6.89806849e-307, 9.34609790e-307,
        1.69121096e-306, 1.05700515e-307, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        3.22643519e-307, 9.79103798e-307, 2.46155235e-312]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [26]:
ide = np.identity(45) 

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr = arr.reshape(3, 33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()

In [34]:
arr.shape

(99,)

In [35]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [43]:
ar.ndim

2

In [44]:
ar.nbytes

36

In [46]:
one = np.array([1,3,4,634,2])

In [50]:
one.argmax()

3

In [51]:
one.argmin()

0

In [52]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.argmin()

8

In [55]:
ar.argmax()

6

In [56]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [57]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [58]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [60]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [62]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [65]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [66]:
[324, 34] + [34, 546]

[324, 34, 34, 546]

In [67]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [69]:
ar.sum()

29

In [70]:
ar.max()

7

In [71]:
ar.min()

0

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
type(np.where(ar>5))

tuple

In [75]:
np.count_nonzero(ar)

8

In [76]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [77]:
ar[1,2] = 0

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [79]:
import sys

In [81]:
py_ar = [0,4,55,2]

In [82]:
np_ar = np.array(py_ar)

In [83]:
sys.getsizeof(1) * len(py_ar)

112

In [84]:
np_ar.itemsize * np_ar.size

16